export enum CallType {
    Voice = 1,
    Video = 2,
}

export enum CameraType {
    OffCamera = 0,
    OnCamera = 1,
}

export type RequestCallSettings = {
    rangeRating: number[];
    ping: Array<number | string>;
    supportCallBusy: number;
    checkTimeOut: number;
    echoLossIncallThreshold: number;
    traceroute: null;
    fromNoti: number;
    voipResetTime: number;
    p2pCheckPkgRec: number;
    voipFTimeWifi: number;
    echoLossThreshold: number;
    congestThreshold: number[];
    checkPkgSent: number;
    voipFTime3G: number;
    p2pReNegotiate: number;
    sizeEchoBeforeCall: number;
    checkPkgRec: number;
    rangeRtt: number[];
    rangeRemoteRating: number[];
    logDebug: number;
    dynamicFptime: number;
    p2p: number;
    periodEchoBeforeCall: number;
    dynamicBitrate: number;
    supportDetectCongestion: number;
    supportResumeCall: number;
};

export type RequestCallZRTCConfig = {
    videoNack: boolean;
    bweSendSideHighLoss: number;
    startAudioInConnecting: number;
    autoAgcMaxGain: number;
    checkLevelNoRecord: number;
    farEndAgc: boolean;
    minAudioDelayMs: number;
    audioEchoRouting: number;
    partnerIP: string;
    vidBweMinResetMs: number;
    audioVDLevel: number;
    audFECTP: boolean;
    maxWidth: number;
    minVideoDelayMs: number;
    maxFT: number;
    timebaseEncoding: boolean;
    mobileNwMaxBitrate: number;
    vieHevcDecoder: number;
    audioSampleRate: number;
    audioChannel: number;
    renderFpsLow: number;
    bweSendSideLowLoss: number;
    decreaseBwIntervalMs: number;
    gccAudioStartBitrate: number;
    lowMicMinLvl: number;
    vidBwHldToIncThreshold: number;
    micSource: number;
    audQualityEst: boolean;
    socketReset: boolean;
    bweSendSideLowRttMs: number;
    selectedServerNum: number;
    timeCheckNoRecord: number;
    encodeMaxReset: number;
    audioNSLevel: number;
    maxPacketSize: number;
    codecMaxFps: number;
    audioHighPassFilter: boolean;
    fallbackServers: number;
    gccAudio: boolean;
    maxHeight: number;
    bwProfiles: Array<{
        res: number;
        audioFrameTime: number;
        fps: number;
        bitrate: number;
        id: number;
        audioBitrate: number;
        requireRttMs: number;
        audioSampleRate: number;
    }>;
    vieFastStartPer: number;
    agcMaxLevel: number;
    maxVideoDelayMs: number;
    gccMode: number;
    vieSuspendBwKbit: number;
    audioEncodeWorker: boolean;
    audioNack: boolean;
    startupBitrate: number;
    audioHwEngine: boolean;
    audioVoiceDetection: boolean;
    selectServer2Side: number;
    numberAudioDeviceReset: number;
    nwPipe: boolean;
    bweSendSideHighRttMs: number;
    vieHevcEncEnable: number;
    vieMaxDecodeTimeMs: number;
    voiceDetect: boolean;
    lowMicMaxLvl: number;
    audioJitterMax: number;
    minBitrate: number;
    aecmInternalRouting: number;
    appLog: number;
    agcGain: number;
    maxBitrate: number;
    h264Decoder: number;
    vieEffectType: number;
    checkLevelAudioDeviceReset: number;
    numSelectedServer: number;
    maxDurCheckNoRecord: number;
    zone: number;
    keyFrameIntervalMs: number;
    turnOffCameraBadNw: boolean;
    feedFpsToBwe: boolean;
    jitterOptimize: number;
    audioNoiseSuppression: boolean;
    audioEngine: boolean;
    hevcCoef: number;
    qpMax: number;
    gccEarlyCall: boolean;
    selectedServer: number;
    durationCheckNoReportSec: number;
    srtpMode: number;
    aecForMobile: boolean;
    FECTimeCheck: number;
    audioDeviceLayer: number;
    autoAgc: boolean;
    audioEchoCancellation: boolean;
    encodeFpsNormalThreshold: number;
    frameDropper: boolean;
    startMicLevel: number;
    vidBwHoldToInc: number;
    maxAudioDelayMs: number;
    increaseBwStepByStep: boolean;
    increaseBwIntervalMs: number;
    agcMode: number;
    calcAudQuality: number;
    cacheType: number;
    audioGainControl: boolean;
    qpMin: number;
    dynamicDevice: number;
    newRating: boolean;
    audioEchoLevel: number;
    preConnectExpire: number;
    opusComplex: number;
    hwVideoEncoder: boolean;
    poorSignalTime: number;
    audioBitrate: number;
    audioFastAccelarate: boolean;
    lossPkgRatePoor: number;
    supportTCP: number;
    x264Preset: string;
    gccSuspendVideoLowBitrate: boolean;
};

export type RequestCallUser = {
    toId: number;
    msg: string | null;
    settings: RequestCallSettings;
    fec: { enable: number };
    rtpIP: string;
    changeZRTP: { enable: number; threshold: number };
    video: { enable: number };
    fromId: number;
    /**
     * ZRTC config - Zalo Real-Time Communication Configuration
     */
    zrtc_config: RequestCallZRTCConfig;
    sessId: string;
    rtcpIP: string;
    protocol: number;
    servers: Array<{
        rtcpaddr: string;
        rtpIPv6: string;
        rtcpIPv6: string;
        spTcp: number;
        rtpaddr: string;
    }>;
    showDebugInfo: number;
    id: number;
    ts: number;
    status: number;
};

export type RequestCallGroupServer = {
    rtpaddr: string;
    rtcpaddr: string;
    rtpaddrIPv6: string;
    rtcpaddrIPv6: string;
};

export type RequestCallGroupSpatialLayer = {
    presetIdx: number;
    bitrateKbps: number;
    factorNum: number;
    minBitrateKbps: number;
    fps: number;
    factorDen: number;
};

export type RequestCallGroupGroupCall = {
    codec: number;
    spatialLayers: RequestCallGroupSpatialLayer[];
    temporalNum: number;
    paddingRatio: number;
    useBwProfile: boolean;
    maxDecodeAllowMs: number;
    maxEncodeAllowMs: number;
    partnerTimeout: number;
};

export type RequestCallGroupZRTCConfig = {
    vidThresholdBitrate: number;
    minShrScreenRes: number;
    maxMbBr: number;
    videoNack: boolean;
    audioNoVoiceFrameSize: number;
    bweSendSideHighLoss: number;
    checkLevelNoRecord: number;
    pingJson: null | Record<string, unknown>;
    audioFecInband: boolean;
    minAudioDelayMs: number;
    audioEchoRouting: number;
    gccPlt: boolean;
    audioDtx: boolean;
    vidBweMinResetMs: number;
    audioVDLevel: number;
    timeInitStat: number;
    maxFT: number;
    maxWidth: number;
    minVideoDelayMs: number;
    vidInitFormatInStart: boolean;
    maxRecvAudio: number;
    maxShrScreenRes: number;
    timebaseEncoding: boolean;
    setSocketDF: number;
    noRecvPartnerMute: boolean;
    rateControl: number;
    minMbShrScreenBr: number;
    audioSampleRate: number;
    hwBitrateMode: number;
    audioChannel: number;
    renderFpsLow: number;
    bweSendSideLowLoss: number;
    voiceProbability: number;
    gccOverheadNack: boolean;
    maxResetDeviceBySlow: number;
    decreaseBwIntervalMs: number;
    partnerLimitVQ: boolean;
    encodeFpsLowThreshold: number;
    vidBwHldToIncThreshold: number;
    micSource: number;
    slowFpsThreshold: number;
    audioFrameTime: number;
    bweSendSideLowRttMs: number;
    maxRetryInitZRTP: number;
    poorSignalPeriod: number;
    timeCheckNoRecord: number;
    encodeMaxReset: number;
    audioNSLevel: number;
    resSlowEncode: number;
    maxLogDuration: number;
    retryNwTimeMs: number;
    encodeFpsNormal: number;
    maxPacketSize: number;
    codecMaxFps: number;
    noRtcpDecByStep: boolean;
    minShrScreenBr: number;
    audioHighPassFilter: boolean;
    minMbBr: number;
    maxHeight: number;
    agcMaxLevel: number;
    vieMaxEncodeTimeMs: number;
    maxVideoDelayMs: number;
    gccMode: number;
    audioEncodeWorker: boolean;
    audioNack: boolean;
    retryNwQueue: number;
    audioHwEngine: boolean;
    audioVoiceDetection: boolean;
    startupBitrate: number;
    noRtcpDecBwTime: number;
    agcTargetLevelInternal: number;
    encodeFpsLow: number;
    numberAudioDeviceReset: number;
    vieMaxSlowDurMs: number;
    nwPipe: boolean;
    rembPacket: boolean;
    bweSendSideHighRttMs: number;
    qualityStorage: number;
    vieMaxDecodeTimeMs: number;
    srtpNoSeq: number;
    svcDecMod: number;
    voiceDetect: boolean;
    videoEncoderFb: boolean;
    lossPkgRateNormal: number;
    audioJitterMax: number;
    audioEchoLevelInternal: number;
    minBitrate: number;
    aecmInternalRouting: number;
    h264ToolboxTsFix: boolean;
    maxMbShrScreenBr: number;
    agcGain: number;
    maxBitrate: number;
    h264Decoder: number;
    autoHangupTime: number;
    captureFpsNormal: number;
    gccPacingFactor: number;
    checkLevelAudioDeviceReset: number;
    audioLevelHeader: boolean;
    maxDurCheckNoRecord: number;
    maxShrScreenBr: number;
    keyFrameIntervalMs: number;
    removeUnusedReceiver: boolean;
    jitterOptimize: number;
    audioNoiseSuppression: boolean;
    useZlsBwProfile: boolean;
    vidThresholdTimeMs: number;
    audioEngine: boolean;
    qpMax: number;
    durationCheckNoReportSec: number;
    vidStableTimeMs: number;
    aecForMobile: boolean;
    videoBwRttLimit: boolean;
    audioDeviceLayer: number;
    timeTryTCP: number;
    audioEchoCancellation: boolean;
    agcTargetLevel: number;
    audioEchoComfortNoise: boolean;
    encodeThread: number;
    vieEncBrNotWorkDur: number;
    x264Tune: string;
    audioLevelEstimate: boolean;
    timeCheckAutoMute: number;
    jitterPostponeDecode: number;
    maxDurAudioDeviceReset: number;
    autoCheckRoaming: boolean;
    overusingBwe: number;
    vieEncBrNotWorkFx: boolean;
    encodeFpsNormalThreshold: number;
    echoCallPeriod: number;
    vieEncBrNotWorkThresh: number;
    jbMs: number;
    frameDropper: boolean;
    vidBwHoldToInc: number;
    srtpKey: string;
    startMicLevel: number;
    maxAudioDelayMs: number;
    increaseBwStepByStep: boolean;
    increaseBwIntervalMs: number;
    minDurCheckSlow: number;
    vidBweLimitRate: number;
    vieEmptyOffNackTimeMs: number;
    agcMode: number;
    fastVQR: boolean;
    numSlowTimes: number;
    muteLimitVQ: number;
    audioGainControl: boolean;
    pingAlivePeriod: number;
    qpMin: number;
    dynamicDevice: number;
    nalHeaderSize: number;
    selectTimeoutMs: number;
    mtkHwVideoDecoder: boolean;
    audioEchoLevel: number;
    audioNoVoiceBitrate: number;
    opusComplex: number;
    hwVideoEncoder: boolean;
    poorSignalTime: number;
    normalSignalTime: number;
    vidBweLimitThreshold: number;
    gccCwndMs: number;
    audioBitrate: number;
    audioFastAccelarate: boolean;
    lossPkgRatePoor: number;
    mtkHwSupport: boolean;
    supportTCP: number;
    x264Preset: string;
    incResTime: number;
    groupcall: RequestCallGroupGroupCall;
};

export type RequestCallGroupCallSetting = {
    servers: RequestCallGroupServer[];
    showDebugInfo: number;
    session: string;
    zrtcConfig: RequestCallGroupZRTCConfig;
    logDebug: number;
};

export type RequestCallGroupParams = {
    callId: number;
    toId: number[];
    msg: string;
    maxUsers: number;
    gridMaxUser: number;
    groupId: number;
    callSetting: RequestCallGroupCallSetting;
    hostCall: number;
    fromId: number;
    noise: Record<string, number>;
    failedId: Record<string, unknown>;
    id: number;
    ts: number;
    status: number;
};

export type RequestCallGroup = {
    msg: string | null;
    partnerIds: string[];
    hostCall: number;
    params: RequestCallGroupParams;
    status: number;
};

export type RequestCallConfig = {
    calleeId: number;
    err: number;
    data: null;
    callerId: number;
};

export type RequestCallCancel = {
    calleeId: number;
    callerId: number;
};
